# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  
  #okd4-services
  config.vm.define "okd4-services" do |node|
  config.vm.provision "shell", path: "init_common.sh"
  config.vm.provision "shell", path: "bootstrap_services.sh"
  
  node.vm.box = "mpaulo/server-gui-centos-8"
  node.vm.hostname = "okd4-services.labor.lan"
  node.vm.network "private_network", ip: "172.16.16.50"

  node.vm.provider "virtualbox" do |v|
    v.name = "tmaster"
    v.memory = 1024*4
    v.cpus = 4
    v.gui = true
  end
end

=begin
  # Kubernetes Worker Nodes
  NodeCount = 8

  (1..NodeCount).each do |i|
  
    config.vm.define "tworker#{i}" do |node|

      node.vm.box = "ubuntu/focal64"
      #node.vm.box_check_update = false
      #node.vm.box_version = "3.1.12"
      node.vm.hostname = "tworker#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.22#{i}"

      node.vm.provider "virtualbox" do |v|
        #v.name = "kworker#{i}"
        v.memory = 1024*8
        v.cpus = 4
        #v.gui = true
      end

      #node.vm.provision "shell", path: "bootstrap_kworker.sh"

    end
  end
=end

end
