# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "client192" do |node|
    #node.vm.box = "ubuntu/focal64"
    node.vm.box = "centos/8"
    node.vm.hostname = "client192.example.com"
    node.vm.network "private_network", ip: "192.168.56.10"
    node.vm.synced_folder "./", "/vagrant"

    node.vm.provider "virtualbox" do |v|
      v.memory = 1024*2
      v.cpus = 2
    end
    #node.vm.provision "shell", path: "bootstrap_kmaster.sh"
    node.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf install -y git tmux python3
    git clone https://github.com/floggy22/initscript.git
    echo "Enable ssh password authentication"
    sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
    systemctl reload sshd

    echo "Set root password"
    echo -e "kubeadmin\nkubeadmin" | passwd root >/dev/null 2>&1
    echo "export TERM=xterm" >> /etc/bash.bashrc
    SHELL
  end

  config.vm.define "router192" do |node|
    node.vm.box = "ubuntu/focal64"
    #node.vm.box = "centos/8"
    node.vm.hostname = "router192.example.com"
    node.vm.network "private_network", ip: "192.168.56.2"
    node.vm.synced_folder "./", "/vagrant"

    node.vm.provider "virtualbox" do |v|
      v.memory = 1024*2
      v.cpus = 2
    end
    #node.vm.provision "shell", path: "bootstrap_kmaster.sh"
    node.vm.provision "shell", inline: <<-SHELL
    apt update
    apt upgrade -y
    apt install -y git tmux python3
    git clone https://github.com/floggy22/initscript.git
    echo "Enable ssh password authentication"
    sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
    systemctl reload sshd

    echo "Set root password"
    echo -e "kubeadmin\nkubeadmin" | passwd root >/dev/null 2>&1
    echo "export TERM=xterm" >> /etc/bash.bashrc
    SHELL
  end

end