apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc190
spec:
  #volumeName: foo-pv
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 190Mi