# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "server" do |node|
    node.vm.box = "ubuntu/focal64"
    node.vm.box_check_update = false
    node.vm.hostname = "server.labor.lan"
    node.vm.network "public_network", bridge: ""
    node.vm.synced_folder "./", "/vagrant"
  
    node.vm.provider "virtualbox" do |v|
      #v.name = ""
      v.memory = 512
      v.cpus = 1
    end
    
    node.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y bind9
      cp /vagrant/dns/* /etc/bind/.
      systemctl restart bind9
    SHELL
    #node.vm.provision "shell", path: "/client/add_dns_ubuntu.sh"
  end

   config.vm.provision "shell", inline: <<-SHELL
     apt update
     apt upgrade -y
     sed -i 's/^PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
     echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
     systemctl reload sshd
     echo -e "kubeadmin\nkubeadmin" | passwd root >/dev/null 2>&1
     #apt-get install -y apache2
   SHELL
end
