# App mit https
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy-gold
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-gold
  template:
    metadata:
      labels:
        run: nginx-gold
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      initContainers:
      - name: web-content
        image: ubuntu
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: 
          - "/bin/bash"
        args:
          - "-c" 
          - "apt update && apt install -y git && cd /webdata && git clone https://github.com/floggy22/otest.git && cp otest/webtest/index_gold.html index.html && rm otest -rf"
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"