# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster" do |node|
  
    node.vm.box = "ubuntu/focal64"
    #node.vm.box_check_update = true
    #node.vm.box_version = "3.1.12"
    node.vm.hostname = "kmaster.labor.lan"
    node.vm.network "private_network", ip: "172.16.16.110"
  
    node.vm.provider "virtualbox" do |v|
      #v.name = "kmaster"
      v.memory = 2048
      v.cpus = 2
    end
    node.vm.provision "shell", path: "bootstrap_kmaster.sh"
  
  end


  # Kubernetes Worker Nodes
  NodeCount = 2

  (1..NodeCount).each do |i|

    config.vm.define "kworker#{i}" do |node|

      node.vm.box = "ubuntu/focal64"
      #node.vm.box_check_update = false
      #node.vm.box_version = "3.1.12"
      node.vm.hostname = "kworker#{i}.labor.lan"
      node.vm.network "private_network", ip: "172.16.16.11#{i}"

      node.vm.provider "virtualbox" do |v|
        #v.name = "kworker#{i}"
        v.memory = 2048
        v.cpus = 2
        #v.gui = true
      end

      node.vm.provision "shell", path: "bootstrap_kworker.sh"

    end
  end
end
