apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
  labels:
    app: myapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myappcontainer6
        image: gitlab.labor.lan:5050/root/test2/nginx
        ports: 
        - containerPort: 80
      imagePullSecrets:
        - name: gitlab
