apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-data1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /var/nfs/general/1
    server: nfsserver.labor.lan