apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-data
  labels:
    app: myapp
spec:
  #volumeName: foo-pv
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi