# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV['VAGRANT_NO_PARALLEL'] = 'yes'


Vagrant.configure(2) do |config|
  # Kubernetes Worker Nodes
  NodeCount = 4

  (1..NodeCount).each do |i|

    config.vm.define "node#{i}" do |node|

      node.vm.box = "ubuntu/focal64"
      #node.vm.box_check_update = false
      #node.vm.box_version = "3.1.12"
      node.vm.hostname = "node#{i}.labor.lan"
      node.vm.network "private_network", ip: "172.16.16.20#{i}"

      node.vm.provider "virtualbox" do |v|
        #v.name = "kworker#{i}"
        v.memory = 1024*2
        v.cpus = 2
        #v.gui = true
      end

      #node.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end

 

    config.vm.provision "shell", path: "bootstrap.sh"
  
    # Kubernetes Master Server
    config.vm.define "ansible" do |node|
    
      node.vm.box = "ubuntu/focal64"
      #node.vm.box_check_update = true
      #node.vm.box_version = "3.1.12"
      node.vm.hostname = "ansible.labor.lan"
      node.vm.network "private_network", ip: "172.16.16.200"
    
      node.vm.provider "virtualbox" do |v|
        #v.name = "kmaster"
        v.memory = 1024*2
        v.cpus = 2
      end
      node.vm.provision "shell", path: "bootstrap_ansible.sh"
  end
  
end
