- name: Update Server
  hosts: nodes
  remote_user: root

  tasks:
    - name: Update System
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes