- name: Install zsh
  hosts: nodes
  remote_user: root
  
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
    roles:
      - viasite-ansible.zshzsh