---
- name: Install Docker and Enable SSH with Password Authentication
  hosts: localhost
  become: yes
  vars:
    user_name: martin
  tasks:

    - name: Install required packages for Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's repository to APT sources
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes
   
    - name: Add user "{{ user_name }}"
      ansible.builtin.user:
        name: "{{ user_name }}"
        append: yes
        shell: /bin/bash
        groups: docker
        createhome: no
      
