# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Worker Nodes
  NodeCount = 4

  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|

      node.vm.box = "ubuntu/bionic64"
      node.vm.box_check_update = false
      node.vm.hostname = "node#{i}.example.com"
      node.vm.network "private_network", ip: "172.16.16.20#{i}"

      node.vm.provider "virtualbox" do |v|
        #v.name = "kworker#{i}"
        v.memory = 4096
        v.cpus = 4
        #v.gui = true
      end

      #node.vm.provision "shell", path: "bootstrap_kworker.sh"

    end
  end

  config.vm.define "ansible" do |node|

    node.vm.box = "ubuntu/focal64"
    node.vm.box_check_update = false
    node.vm.hostname = "ansible.example.com"
    node.vm.network "private_network", ip: "172.16.16.200"
  
    node.vm.provider "virtualbox" do |v|
      #v.name = ""
      v.memory = 4096
      v.cpus = 4
    end
    #node.vm.provision "shell", path: "bootstrap_ansible.sh"
  end

end
