apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvbbb88
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  storageClassName: ""
  mountOptions:
    - hard
    - nfsver=4.0
  nfs:
    path: /var/nfs/general
    server: 172.16.16.20